### ISSUE TITLE
Ability to remove the single-player and multiplayer buttons

### ISSUE THREAD

**Issue by azzRPG** [admin-else/MicroBloat#1]
Probably not the most useful feature, but if it is, this mod would be a great replacement (in my opinion) for the "Minimal Menu" mod, which has not been updated to 1.19.2.

**Comment by admin-else** [comment]
thanks azzRPG for the suggestion ill do taht now (:

**Comment by azzRPG** [comment]
Nice! 
Ty for this wonderful mod

**Comment by Cabbasca** [comment]
I got the Benz and got beef, finna cook it (err)
Big flawless diamonds, bitch, they sit on my wrist (ooh)
They said they wan' sign a lil' kid for some cheese (noble, this is crazy)
I told 'em it's "Fuck 'em, I'm already rich" (rich)
