### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by azzRPG** [admin-else/MicroBloat#2]
Can you please update this mod to 1.19.3? Unfortunately, the version for 1.19.2 crashes the game
https://mclo.gs/pj9YbVw

In any case, thanks for this mod.

**Comment by admin-else** [comment]
I am working on an update for 1.19.3 i will fix the crash or try to.

**Comment by admin-else** [comment]
This might take some time mojang added a feature to help them align buttons more easily this breaks my mod entirely.

**Comment by azzRPG** [comment]
Thanks!

**Comment by Cabbasca** [comment]
I got the Benz and got beef, finna cook it (err)
Big flawless diamonds, bitch, they sit on my wrist (ooh)
They said they wan' sign a lil' kid for some cheese (noble, this is crazy)
I told 'em it's "Fuck 'em, I'm already rich" (rich)
